### ISSUE TITLE
請教一下

### ISSUE THREAD

**Issue by jeok70** [der3318/SentimentAnalyzer#1]
請問作者，您這個 source 可以用嗎？
有沒有發表論文呢？

**Comment by der3318** [comment]
source可自由使用，但裡面有使用到其他作者的lib(如結巴斷詞系統)
若也有需要的話，可能要再注意一下它的license
因探討的程度不深，沒有論文的發表

**Comment by jeok70** [comment]
請問你是台大資工系的嘛!?

**Comment by der3318** [comment]
是，不過還沒畢業

**Comment by jeok70** [comment]
那關於權重值得探討這些部分，請教一下，你是從哪裡找的!?

**Comment by der3318** [comment]
大部分是搜尋 Semantic Orientation Point Mutual Information 和 Neuro-Linguistic Programming 的相關資料查到的
